### Get all competitions
GET http://localhost:8080/api/competitions
Authorization: Bearer {{access_token}}

### Get active competitions
GET http://localhost:8080/api/competitions/active
Authorization: Bearer {{access_token}}

### Get status of competitions for the selected school year
GET http://localhost:8080/api/competitions/status/2324
Authorization: Bearer {{access_token}}

### Get Random Competition
GET http://localhost:8080/api/competitions/random
Authorization: Bearer {{access_token}}

### Get access Token for creating and updating
POST http://localhost:8081/realms/demo/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&
client_id=quarkus-client&
username=admin&
password=admin

> {% client.global.set("access_token", response.body.access_token); %}

### Get access Token for creating and updating
POST https://auth.htl-leonding.ac.at/realms/wettbewerbsdatenbank/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&
client_id=quarkus-client&
username=it210157&
password=

> {% client.global.set("access_token", response.body.access_token); %}

### Test
GET https://auth.htl-leonding.ac.at/admin/realms/wettbewerbsdatenbank/users/count?enabled=true
Authorization: Bearer {{access_token}}

### Create a new competition
POST http://localhost:8080/api/competitions
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "Project Award",
  "link": "https://htl-leonding.ac.at",
  "deadline": "Noch nicht freigegeben",
  "deadline_date": "2026-01-01",
  "prize": "5€ mci Gutschein auf Bauer sein Nacken",
  "information_material": "https://edufs.edu.htl-leonding.ac.at",
  "submission_forms": "https://edufs.edu.htl-leonding.ac.at/moodle",
  "contact": "p.bauer@htl-leonding.ac.at",
  "is_active": true,
  "school_year": "2526",
  "is_relevant": true
}

### Delete competition
DELETE http://localhost:8080/api/competitions/1
Authorization: Bearer {{access_token}}

### Update a competition
PUT http://localhost:8080/api/competitions/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "Project Award",
  "link": "https://htl-leonding.ac.at",
  "deadline": "Noch nicht freigegeben",
  "deadline_date": "2026-01-01",
  "prize": "5€ mci Gutschein auf Bauer sein Nacken",
  "information_material": "https://edufs.edu.htl-leonding.ac.at",
  "submission_forms": "https://edufs.edu.htl-leonding.ac.at/moodle",
  "contact": "p.bauer@htl-leonding.ac.at",
  "is_active": true,
  "school_year": "2526",
  "is_relevant": false
}


### Get all Projects
GET http://localhost:8080/api/projects
Authorization: Bearer {{access_token}}

### Add a Project to a competition
POST http://localhost:8080/api/projects
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "competition_id": 1,
    "name": "Test Project",
    "status": "Abgeschlossen",
    "next_step": "Abgabe",
    "contributors": "Philip Pfarrhofer, Hahn Alexander"
}

### Update a Project
PUT http://localhost:8080/api/projects/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "competition_id": 1,
  "name": "Updated Project",
  "status": "In Progress",
  "next_step": "Scram Meeting",
  "contributors": "Philip Pfarrhofer, Alexander Hahn"
}

### Delete a Project
DELETE http://localhost:8080/api/projects/2
Authorization: Bearer {{access_token}}


### Get all Changes
GET http://localhost:8080/api/changes
Authorization: Bearer {{access_token}}

### Get all Changes for a competition
GET http://localhost:8080/api/changes/competition/1
Authorization: Bearer {{access_token}}

### Delete image
DELETE http://localhost:8080/api/images/1
Authorization: Bearer {{access_token}}