@REALM={{KEYCLOAK_URL}}/realms/wettbewerbsdatenbank
@TOKEN_ENDPOINT={{wellknown.token_endpoint}}
@ACCESS_TOKEN={{login.access_token}}

# open http://localhost:8000/admin/master/console/#/demo/clients/ and navigate to backend->credentials and paste here
@CLIENT_SECRET=o1BWGJt5QlS0D3yn9HtLXXWI5W6DqjxL

###
# @name wellknown
GET {{REALM}}/.well-known/openid-configuration
###
# @name login
# @ref wellknown
POST {{TOKEN_ENDPOINT}}
Content-Type: application/x-www-form-urlencoded

client_secret={{CLIENT_SECRET}}&client_id=backend&username=joe&password=password&grant_type=password&redirect_uri=http%3A%2F%2Fwww.htl-leonding.ac.at

### hello ###
GET {{BACKEND_URL}}/hello

###
# @name posts
# @ref login
GET {{BACKEND_URL}}/posts
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}
###

