version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: wettbewerbs-database
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "5423:5432"  # host:container
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  keycloak:
    image: pfarrhoferphilip/wettbewerbs-keycloak
    container_name: wettbewerbs-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/demo
      KC_DB_USERNAME: demo
      KC_DB_PASSWORD: demo
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
    networks:
      - backend


  app:
    image: pfarrhoferphilip/wettbewerbs-backend
    container_name: wettbewerbs-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/demo
      QUARKUS_DATASOURCE_USERNAME: demo
      QUARKUS_DATASOURCE_PASSWORD: demo
    ports:
      - "8080:8080"
    networks:
      - backend

  frontend:
    image: pfarrhoferphilip/wettbewerbs-frontend
    container_name: wettbewerbs-frontend
    ports:
      - "4200:80"  # Host port 4200 maps to nginx's port 80
    networks:
      - backend

networks:
  backend:
