INSERT INTO competition (name, link, deadline, deadline_date, prize, information_material, submission_forms, contact, is_active, date_created, school_year, created_by, is_relevant, is_not_relevant_info) VALUES
-- Austria Cyber Security Challenge
('Austria Cyber Security Challenge (ACSC)',
 'https://verbotengut.at/',
 'Anmeldung Online Qualifying Austria Cyber Security Challenge 2023 war bis 31.08. möglich. Ergebnisse noch unklar',
 '2023-08-21',
 'NA',
 'https://verbotengut.at/anmeldung/',
 'https://google.com',
 'office@cybersecurityaustria.at',
 true,
 '2023-09-05',
 '2324',
 'e.baar',
 true,
 'Wettbewerb ist ein externer Wettbewerb'),

-- Austrian Skills
('Austrian Skills',
 'https://www.wko.at/site/skillsaustria/start.html',
 'AustrianSkills 2023 findet am 4.–7.10.2023 in Wels und 23.–26.11.2023 in Salzburg statt',
 '2023-08-21',
 'Gewinner kommt zum World Skills, zweiter zu Euro Skills',
 'NA',
 'NA',
 'https://www.wko.at/site/skillsaustria/whoiswho.html',
 true,
 '2023-09-05',
 '2324',
 'e.baar',
 true,
 'Wettbewerb ist ein externer Wettbewerb'),

-- Fiktive Wettbewerbe
('HTL Coding Cup',
 'https://htlcodingcup.at',
 '31.12.2025',
 '2023-08-21',
 'Sachpreise und Praktika bei IT-Firmen',
 'https://htlcodingcup.at/downloads/broschuere.pdf',
 'https://htlcodingcup.at/anmeldung',
 'kontakt@htlcodingcup.at',
 true,
 '2025-07-07',
 '2425',
 'e.baar',
 false,
 'Wettbewerb ist ein externer Wettbewerb'),

('European Robotics Competition',
 'https://robotics-europe.org',
 '15.08.2025',
 '2023-08-21',
 'Teilnahme an der World Robotics Championship',
 'https://robotics-europe.org/info',
 'https://robotics-europe.org/register',
 'support@robotics-europe.org',
 true,
 '2025-07-07',
 '2425',
 'e.baar',
 true,
 'Wettbewerb ist ein externer Wettbewerb'),

('Young Engineers Challenge',
 'https://youngengineers.at',
 '01.09.2025',
 '2023-08-21',
 'Stipendium für technische Studiengänge',
 'https://youngengineers.at/broschuere.pdf',
 'https://youngengineers.at/formular',
 'info@youngengineers.at',
 false,
 '2025-04-07',
 '2425',
 'e.baar',
 false,
 'Wettbewerb ist ein externer Wettbewerb'),

('AI Innovation Sprint',
 'https://ai-sprint.eu',
 '30.03.2025',
 '2025-03-10',
 'High‑end GPU Workstations',
 'https://ai-sprint.eu/info',
 'https://ai-sprint.eu/register',
 'contact@ai-sprint.eu',
 true,
 '2025-03-15',
 '2425',
 'e.baar',
 true,
 'Wettbewerb ist ein externer Wettbewerb'),

('GreenTech Future Award',
 'https://greentechfuture.org',
 '15.04.2025',
 '2025-03-01',
 '5.000€ Umweltstipendium',
 'https://greentechfuture.org/material',
 'https://greentechfuture.org/apply',
 'office@greentechfuture.org',
 false,
 '2025-03-18',
 '2425',
 'e.baar',
 false,
 'Wettbewerb ist ein externer Wettbewerb'),

('Young Innovators Europe',
 'https://yinno.eu',
 '20.05.2025',
 '2025-04-01',
 'Mentoring + Reisen nach Brüssel',
 'https://yinno.eu/docs',
 'https://yinno.eu/apply',
 'support@yinno.eu',
 true,
 '2025-04-10',
 '2425',
 'e.baar',
 true,
 'Wettbewerb ist ein externer Wettbewerb'),

('Space Engineering Challenge',
 'https://spacechallenge.eu',
 '01.06.2025',
 '2025-04-15',
 'Besuch im ESA‑Control Center',
 'https://spacechallenge.eu/info',
 'https://spacechallenge.eu/form',
 'space@esa.org',
 true,
 '2025-04-20',
 '2425',
 'e.baar',
 true,
 'Wettbewerb ist ein externer Wettbewerb'),

('Digital Health Hackathon',
 'https://healthhack.eu',
 '10.07.2025',
 '2025-05-10',
 'Geldpreise & Praktika',
 'https://healthhack.eu/docs',
 'https://healthhack.eu/register',
 'mail@healthhack.eu',
 false,
 '2025-05-11',
 '2425',
 'e.baar',
 false,
 'Wettbewerb ist ein externer Wettbewerb'),

('European Renewable Energy Contest',
 'https://resenergy.eu',
 '20.07.2025',
 '2025-05-20',
 'Reise nach Kopenhagen',
 'https://resenergy.eu/material',
 'https://resenergy.eu/apply',
 'info@resenergy.eu',
 true,
 '2025-05-22',
 '2425',
 'e.baar',
 true,
 'Wettbewerb ist ein externer Wettbewerb'),

('Cyber Defense Junior League',
 'https://cdjl.eu',
 '05.08.2025',
 '2025-06-01',
 'Hardware‑Security‑Toolkit',
 'https://cdjl.eu/guide',
 'https://cdjl.eu/signup',
 'team@cdjl.eu',
 true,
 '2025-06-05',
 '2425',
 'e.baar',
 true,
 'Wettbewerb ist ein externer Wettbewerb'),

('Innovative Mobility Award',
 'https://mobilityaward.eu',
 '22.08.2025',
 '2025-06-15',
 'E‑Scooter & Verkehrs‑Workshop',
 'https://mobilityaward.eu/info',
 'https://mobilityaward.eu/register',
 'office@mobilityaward.eu',
 false,
 '2025-06-18',
 '2425',
 'e.baar',
 false,
 'Wettbewerb ist ein externer Wettbewerb'),

('Junior Data Science Cup',
 'https://datasciencecup.eu',
 '30.08.2025',
 '2025-06-20',
 'NVIDIA‑Zertifikate',
 'https://datasciencecup.eu/docs',
 'https://datasciencecup.eu/apply',
 'support@datasciencecup.eu',
 true,
 '2025-06-23',
 '2425',
 'e.baar',
 true,
 'Wettbewerb ist ein externer Wettbewerb'),

('Tech Entrepreneurs League',
 'https://tel-league.eu',
 '01.09.2025',
 '2025-06-30',
 'Startup Coaching + 2.000€',
 'https://tel-league.eu/info',
 'https://tel-league.eu/join',
 'hello@tel-league.eu',
 true,
 '2025-07-01',
 '2425',
 'e.baar',
 true,
 'Wettbewerb ist ein externer Wettbewerb'),

('European Drone Masters',
 'https://dronemasters.eu',
 '15.09.2025',
 '2025-07-10',
 'Profi‑Drohnenkits',
 'https://dronemasters.eu/docs',
 'https://dronemasters.eu/register',
 'contact@dronemasters.eu',
 true,
 '2025-07-12',
 '2425',
 'e.baar',
 true,
 'Wettbewerb ist ein externer Wettbewerb'),

('Smart City Innovation Cup',
 'https://smartcitycup.eu',
 '20.09.2025',
 '2025-07-15',
 'Reise zu Smart‑City‑Konferenzen',
 'https://smartcitycup.eu/material',
 'https://smartcitycup.eu/form',
 'mail@smartcitycup.eu',
 false,
 '2025-07-17',
 '2425',
 'e.baar',
 false,
 'Wettbewerb ist ein externer Wettbewerb'),

('NextGen Robotics League',
 'https://ng-robotics.eu',
 '01.10.2025',
 '2025-08-01',
 'Robotik‑Kits & Zertifikate',
 'https://ng-robotics.eu/info',
 'https://ng-robotics.eu/register',
 'support@ng-robotics.eu',
 true,
 '2025-08-03',
 '2425',
 'e.baar',
 true,
 'Wettbewerb ist ein externer Wettbewerb'),

('EcoTech Builders Challenge',
 'https://ecotechbuilders.eu',
 '12.10.2025',
 '2025-08-10',
 'Nachhaltigkeits‑Workshops',
 'https://ecotechbuilders.eu/docs',
 'https://ecotechbuilders.eu/apply',
 'team@ecotechbuilders.eu',
 false,
 '2025-08-12',
 '2425',
 'e.baar',
 false,
 'Wettbewerb ist ein externer Wettbewerb');


INSERT INTO project (competition_id, name, status, next_step, contributors, date_created) VALUES
-- Projekte für Austria Cyber Security Challenge (ID vermutlich 1)
(1, 'Secure Login System', 'In Bearbeitung', 'Abschließender Sicherheitstest', 'Anna Meier, Lukas Schwarz', '2025-08-12'),
(1, 'Phishing Awareness Kampagne', 'Abgeschlossen', 'Ergebnisse präsentieren', 'Tom Huber, Sophie Klein', '2025-08-12'),

-- Projekte für Austrian Skills (ID vermutlich 2)
(2, 'CNC Fräsmodul', 'In Bearbeitung', 'Prototyp testen', 'Max Berger, Julia Gruber', '2025-08-12'),
(2, '3D-Druck Wettbewerbsobjekt', 'Idee eingereicht', 'Material beschaffen', 'Stefan Hofer', '2025-08-12'),

-- Projekte für HTL Coding Cup (ID vermutlich 3)
(3, 'Quiz-App für HTL Schüler', 'Abgeschlossen', 'Veröffentlichung im Play Store', 'Nina Wolf, Paul Leitner', '2025-08-12'),

-- Projekte für European Robotics Competition (ID vermutlich 4)
(4, 'Autonomer Linienfolger', 'In Bearbeitung', 'Kalibrierung optimieren', 'Fabian Bauer, Elena Fuchs', '2025-08-12'),

-- Projekte für Young Engineers Challenge (ID vermutlich 5)
(5, 'Energieeffizientes Minihaus', 'Idee eingereicht', 'Pläne finalisieren', 'Laura Steiner, Markus Weber', '2025-08-12');
